# Dependencies

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: Gonzalo Velarde
tagline: 'GV'
description: 'Another personal Website'
url: "https://gonzalovelarde.github.io" # Dirección base de GitHub Pages
baseurl: "/Blog" # Ruta base del proyecto

author:
  name: 'Gonzalo Velarde'
  url: "www.linkedin.com/in/gonzalo-velarde-172bb1120"

plugins:
  - jekyll-paginate
  - jekyll-assets

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/GonzaloVelarde/Blog
