# Dependencies

# Permalinks
permalink:        pretty
relative_permalinks: False

# Setup
title:            Gonzalo Velarde
tagline:          'GV'
description:      'Another personal Website'
baseurl: ""  # Dejar vacío para localhost o dominio raíz
url: "https://gonzalovelarde.github.io/Blog"
# baseurl: "" # Ruta base del proyecto

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo


plugins:
- jekyll-paginate
- jekyll-assets


paginate:         5

# Custom vars
version:          2.1.0


github:
  repo:           https://github.com/poole/hyde
