# Dependencies

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: Gonzalo Velarde
tagline: 'GV'
description: 'Another personal Website'
url: "https://gonzalovelarde.github.io/Blog" 
baseurl: "" # Ruta base del proyecto

author:
  name: 'Gonzalo Velarde'
  url: "www.linkedin.com/in/gonzalo-velarde-172bb1120"

plugins:
  - jekyll-paginate
  - jekyll-assets

# jekyll-archives:
#   enabled:
#     - categories
#   layout: category
#   permalink: /blog/category/:name/

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/GonzaloVelarde/Blog
