# Dependencies

# Permalinks
permalink: /:categories/:title/
# relative_permalinks: True


# Setup
title: Gonzalo Velarde
tagline: 'GV'
description: 'Another personal Website'
url: "https://gonzalovelarde.github.io/Blog"
baseurl: ""

author:
  name: 'Gonzalo Velarde'
  url: "www.linkedin.com/in/gonzalo-velarde-172bb1120"

plugins:
  - jekyll-paginate
  - jekyll-assets

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/GonzaloVelarde/Blog
